# Generated by Django 6.0.5 on 2026-05-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='categoria',
            field=models.CharField(choices=[('Componentes Mecânicos', 'Componentes Mecânicos'), ('Químicos e Pintura', 'Químicos e Pintura'), ('Fluidos e Lubrificantes', 'Fluidos e Lubrificantes'), ('Uniformes', 'Uniformes'), ('EPIs', 'EPIs')], default='Componentes Mecânicos', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='peca',
            name='deposito',
            field=models.CharField(choices=[('tint', 'tint'), ('lb01', 'lb01'), ('ep01', 'ep01'), ('temp', 'temp'), ('pc01', 'pc01'), ('pc02', 'pc02'), ('un01', 'un01')], default='un01', max_length=10, verbose_name='Depósito / Locação'),
        ),
    ]
