# Generated by Django 6.0.5 on 2026-05-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0002_peca_categoria_peca_deposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='locacao',
            field=models.CharField(blank=True, help_text='Ex: Prateleira B - Corredor 2', max_length=100, null=True, verbose_name='Locação / Posição Física'),
        ),
    ]
