# Generated by Django 6.0.5 on 2026-05-23 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0003_peca_locacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peca',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='peca',
            name='deposito',
        ),
        migrations.RemoveField(
            model_name='peca',
            name='finalidade',
        ),
        migrations.RemoveField(
            model_name='peca',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='peca',
            name='locacao',
        ),
        migrations.CreateModel(
            name='HistoricoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('adicionar', 'Entrada'), ('retirar', 'Saída')], max_length=10, verbose_name='Tipo de Operação')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade Movimentada')),
                ('saldo_momento', models.IntegerField(verbose_name='Saldo no Momento')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='pecas.peca', verbose_name='Peça')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Movimentação',
                'verbose_name_plural': 'Histórico de Movimentações',
                'ordering': ['-data_hora'],
            },
        ),
    ]
