# Generated by Django 6.0.5 on 2026-05-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0004_remove_peca_categoria_remove_peca_deposito_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peca',
            options={'verbose_name': 'Peça', 'verbose_name_plural': 'Peças'},
        ),
        migrations.AddField(
            model_name='peca',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='peca',
            name='deposito',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Depósito'),
        ),
        migrations.AddField(
            model_name='peca',
            name='locacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Locação/Prateleira'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade em Estoque'),
        ),
    ]
