# Generated by Django 6.0.5 on 2026-05-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0005_alter_peca_options_peca_categoria_peca_deposito_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peca',
            options={},
        ),
        migrations.RemoveField(
            model_name='peca',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='peca',
            name='deposito',
        ),
        migrations.RemoveField(
            model_name='peca',
            name='locacao',
        ),
        migrations.AlterField(
            model_name='peca',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='peca',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='peca',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
