# Generated by Django 6.0.5 on 2026-05-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0006_alter_peca_options_remove_peca_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peca',
            options={'verbose_name': 'Peça', 'verbose_name_plural': 'Peças'},
        ),
        migrations.AddField(
            model_name='peca',
            name='categoria',
            field=models.CharField(blank=True, choices=[('mecanicos', 'Componentes Mecânicos'), ('quimicos_paintura', 'Químicos e Pintura'), ('fluidos_lubrificantes', 'Fluidos e Lubrificantes'), ('uniformes_epis', 'Uniformes e EPIs')], max_length=30, null=True, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='peca',
            name='deposito',
            field=models.CharField(blank=True, choices=[('pc01', 'PC01'), ('pc02', 'PC02'), ('tint', 'TINT'), ('lb01', 'LB01'), ('temp', 'TEMP'), ('ep01', 'EP01'), ('un01', 'UN01')], max_length=10, null=True, verbose_name='Depósito'),
        ),
        migrations.AddField(
            model_name='peca',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pecas/', verbose_name='Imagem da Peça'),
        ),
        migrations.AddField(
            model_name='peca',
            name='locacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Locação da Peça'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
    ]
