# Generated by Django 6.0.5 on 2026-05-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0007_alter_peca_options_peca_categoria_peca_deposito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='finalidade',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição Operacional e Aplicação'),
        ),
    ]
