# Generated by Django 6.0.5 on 2026-07-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0008_peca_finalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicomovimentacao',
            name='numero_reserva',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Reserva'),
        ),
    ]
