# Generated by Django 6.0.5 on 2026-07-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0009_historicomovimentacao_numero_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomovimentacao',
            name='numero_reserva',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número da Reserva'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='categoria',
            field=models.CharField(blank=True, choices=[('mecanicos', 'Componentes Mecânicos'), ('quimicos_paintura', 'Químicos e Pintura'), ('fluidos_lubrificantes', 'Fluidos e Lubrificantes'), ('uniformes_epis', 'Uniformes e EPIs'), ('pneu_novo', 'Pneu Novo'), ('pneu_recapado', 'Pneu Recapado')], max_length=50, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='deposito',
            field=models.CharField(blank=True, choices=[('pc01', 'PC01'), ('pc02', 'PC02'), ('tint', 'TINT'), ('lb01', 'LB01'), ('temp', 'TEMP'), ('ep01', 'EP01'), ('un01', 'UN01'), ('pne1', 'PNE1 - Depósito de Pneus 1'), ('pne2', 'PNE2 - Depósito de Pneus 2')], max_length=10, null=True, verbose_name='Depósito'),
        ),
    ]
