# Generated by Django 6.0.5 on 2026-07-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0010_alter_historicomovimentacao_numero_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='unidade_medida',
            field=models.CharField(choices=[('unidade', 'Unidade'), ('quilos', 'Quilos'), ('litros', 'Litros')], default='unidade', max_length=10, verbose_name='Unidade de Medida'),
        ),
    ]
