# Generated by Django 6.0.5 on 2026-07-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0011_peca_unidade_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link da Imagem da Peça'),
        ),
    ]
